from foundermode.domain.schema import InvestmentMemo


def render_memo(memo: InvestmentMemo, filename: str | None = None) -> str:
    """
    Renders the Investment Memo into a clean HTML format.
    If filename is provided, writes the content to that file.
    """

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FounderMode Investment Memo</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max_width: 800px;
            margin: 0 auto;
            padding: 2rem;
        }}
        h1 {{
            border-bottom: 2px solid #333;
            padding-bottom: 0.5rem;
        }}
        h2 {{
            color: #2c3e50;
            margin-top: 2rem;
            border-bottom: 1px solid #eee;
        }}
        .section {{
            margin-bottom: 2rem;
            background: #f9f9f9;
            padding: 1.5rem;
            border-radius: 8px;
        }}
        .footer {{
            margin-top: 4rem;
            text-align: center;
            font-size: 0.8rem;
            color: #777;
        }}
    </style>
</head>
<body>
    <h1>Investment Memo</h1>

    <div class="section">
        <h2>Executive Summary</h2>
        <p>{memo.executive_summary}</p>
    </div>

    <div class="section">
        <h2>Market Analysis</h2>
        <p>{memo.market_analysis}</p>
    </div>

    <div class="section">
        <h2>Competitive Landscape</h2>
        <p>{memo.competitive_landscape}</p>
    </div>

    <div class="footer">
        Generated by FounderMode AI
    </div>
</body>
</html>
    """

    if filename:
        with open(filename, "w") as f:
            f.write(html)

    return html
